package com.google.android.gms.internal;

public enum zzai
{
  private final String zzkk;
  
  static
  {
    zzfA = new zzai("ALLOW_LINKER", 10, "allow_linker");
    zzfB = new zzai("ANALYTICS_FIELDS", 11, "analytics_fields");
    zzfC = new zzai("ANALYTICS_PASS_THROUGH", 12, "analytics_pass_through");
    zzfD = new zzai("ANONYMIZE_IP", 13, "anonymize_ip");
    zzfE = new zzai("ANY_OF", 14, "any_of");
    zzfF = new zzai("APP_NAME", 15, "app_name");
    zzfG = new zzai("APP_VERSION", 16, "app_version");
    zzfH = new zzai("ARG0", 17, "arg0");
    zzfI = new zzai("ARG1", 18, "arg1");
    zzfJ = new zzai("ATTRIBUTE", 19, "attribute");
    zzfK = new zzai("ATTRIBUTION_FIELDS", 20, "attribution_fields");
    zzfL = new zzai("AUTO_LINK_DOMAINS", 21, "auto_link_domains");
    zzfM = new zzai("BLACKLISTED_BEHAVIOR", 22, "blacklisted_behavior");
    zzfN = new zzai("CACHE_BUSTER", 23, "cache_buster");
    zzfO = new zzai("CACHE_BUSTER_VALUE", 24, "cache_buster_value");
    zzfP = new zzai("CAMPAIGN_CONTENT_KEY", 25, "campaign_content_key");
    zzfQ = new zzai("CAMPAIGN_CONTENT_OVERRIDE", 26, "campaign_content_override");
    zzfR = new zzai("CAMPAIGN_COOKIE_TIMEOUT", 27, "campaign_cookie_timeout");
    zzfS = new zzai("CAMPAIGN_MEDIUM_KEY", 28, "campaign_medium_key");
    zzfT = new zzai("CAMPAIGN_MEDIUM_OVERRIDE", 29, "campaign_medium_override");
    zzfU = new zzai("CAMPAIGN_NAME_KEY", 30, "campaign_name_key");
    zzfV = new zzai("CAMPAIGN_NAME_OVERRIDE", 31, "campaign_name_override");
    zzfW = new zzai("CAMPAIGN_NO_KEY", 32, "campaign_no_key");
    zzfX = new zzai("CAMPAIGN_SOURCE_KEY", 33, "campaign_source_key");
    zzfY = new zzai("CAMPAIGN_SOURCE_OVERRIDE", 34, "campaign_source_override");
    zzfZ = new zzai("CAMPAIGN_TERM_KEY", 35, "campaign_term_key");
    zzga = new zzai("CAMPAIGN_TERM_OVERRIDE", 36, "campaign_term_override");
    zzgb = new zzai("CAMPAIGN_TRACK", 37, "campaign_track");
    zzgc = new zzai("CATEGORY", 38, "category");
    zzgd = new zzai("CHECK_VALIDATION", 39, "check_validation");
    zzge = new zzai("CHILD_INDEX", 40, "child_index");
    zzgf = new zzai("CLEAR_PERSISTENT_DATA_LAYER_PREFIX", 41, "clear_data_layer_prefix");
    zzgg = new zzai("CLICK_ID", 42, "click_id");
    zzgh = new zzai("CLIENT_INFO", 43, "client_info");
    zzgi = new zzai("COLLECT_ADID", 44, "collect_adid");
    zzgj = new zzai("COMPANY", 45, "company");
    zzgk = new zzai("COMPONENT", 46, "component");
    zzgl = new zzai("CONTENT_DESCRIPTION", 47, "content_description");
    zzgm = new zzai("CONTENT_GROUP", 48, "content_group");
    zzgn = new zzai("CONVERSION_ID", 49, "conversion_id");
    zzgo = new zzai("COOKIE_DOMAIN", 50, "cookie_domain");
    zzgp = new zzai("COOKIE_EXPIRATION", 51, "cookie_expiration");
    zzgq = new zzai("COOKIE_NAME", 52, "cookie_name");
    zzgr = new zzai("COOKIE_PATH", 53, "cookie_path");
    zzgs = new zzai("COOKIE_PATH_COPY", 54, "cookie_path_copy");
    zzgt = new zzai("COUNTRY", 55, "country");
    zzgu = new zzai("CSS_ID", 56, "css_id");
    zzgv = new zzai("CSS_IMPORTANT", 57, "css_important");
    zzgw = new zzai("CSS_PROPERTY", 58, "css_property");
    zzgx = new zzai("CSS_RULE", 59, "css_rule");
    zzgy = new zzai("CSS_VALUE", 60, "css_value");
    zzgz = new zzai("CURRENCY_CODE", 61, "currency_code");
    zzgA = new zzai("CUSTOM_URL_SOURCE", 62, "custom_url_source");
    zzgB = new zzai("CUSTOM_VARS", 63, "custom_vars");
    zzgC = new zzai("CUSTOMER_ID", 64, "customer_id");
    zzgD = new zzai("DATA_LAYER_VERSION", 65, "data_layer_version");
    zzgE = new zzai("DATA_PROVIDER_ID", 66, "data_provider_id");
    zzgF = new zzai("DEBUG", 67, "debug");
    zzgG = new zzai("DECODE", 68, "decode");
    zzgH = new zzai("DECORATE_FORM", 69, "decorate_form");
    zzgI = new zzai("DECORATE_FORMS_AUTO_LINK", 70, "decorate_forms_auto_link");
    zzgJ = new zzai("DECORATE_LINK", 71, "decorate_link");
    zzgK = new zzai("DEFAULT_PAGES", 72, "default_pages");
    zzgL = new zzai("DEFAULT_VALUE", 73, "default_value");
    zzgM = new zzai("DEPENDENCIES", 74, "dependencies");
    zzgN = new zzai("DETECT_FLASH", 75, "detect_flash");
    zzgO = new zzai("DETECT_TITLE", 76, "detect_title");
    zzgP = new zzai("DIMENSION", 77, "dimension");
    zzgQ = new zzai("DISPATCH_ON_FIRE", 78, "dispatch_on_fire");
    zzgR = new zzai("DOMAIN_NAME", 79, "domain_name");
    zzgS = new zzai("DOUBLE_CLICK", 80, "double_click");
    zzgT = new zzai("ECOMMERCE_MACRO_DATA", 81, "ecommerce_macro_data");
    zzgU = new zzai("ECOMMERCE_USE_DATA_LAYER", 82, "ecommerce_use_data_layer");
    zzgV = new zzai("ELEMENT", 83, "element");
    zzgW = new zzai("ELEMENT_ID", 84, "element_id");
    zzgX = new zzai("ELEMENTS", 85, "elements");
    zzgY = new zzai("EMAIL", 86, "email");
    zzgZ = new zzai("EMPLOYEE_RANGE", 87, "employee_range");
    zzha = new zzai("ENABLE_ATTRIBUTION", 88, "enable_attribution");
    zzhb = new zzai("ENABLE_ECOMMERCE", 89, "enable_ecommerce");
    zzhc = new zzai("ENABLE_ALL_VIDEOS", 90, "enable_all_videos");
    zzhd = new zzai("ENABLE_PRODUCT_REPORTING", 91, "enable_product_reporting");
    zzhe = new zzai("ENABLE_REMARKETING_LISTS", 92, "enable_remarketing_lists");
    zzhf = new zzai("ESCAPE", 93, "escape");
    zzhg = new zzai("EVENT_ACTION", 94, "event_action");
    zzhh = new zzai("EVENT_CATEGORY", 95, "event_category");
    zzhi = new zzai("EVENT_LABEL", 96, "event_label");
    zzhj = new zzai("EVENT_VALUE", 97, "event_value");
    zzhk = new zzai("EXCEPTION_DESCRIPTION", 98, "exception_description");
    zzhl = new zzai("EXCEPTION_FATAL", 99, "exception_fatal");
    zzhm = new zzai("EXPERIMENT_COMBINATION", 100, "experiment_combination");
    zzhn = new zzai("EXPERIMENT_ID", 101, "experiment_id");
    zzho = new zzai("EXPERIMENT_KEY", 102, "experiment_key");
    zzhp = new zzai("EXPIRATION_DAY", 103, "expiration_day");
    zzhq = new zzai("EXPIRATION_DATES", 104, "expiration_dates");
    zzhr = new zzai("FAILED_BEHAVIOR", 105, "failed_behavior");
    zzhs = new zzai("FIELDS_TO_SET", 106, "fields_to_set");
    zzht = new zzai("FORCE_SSL", 107, "force_ssl");
    zzhu = new zzai("FORM_OBJECT", 108, "form_object");
    zzhv = new zzai("FUNCTION", 109, "function");
    zzhw = new zzai("FUNCTION_CALL_NAME", 110, "function_call_macro_name");
    zzhx = new zzai("GROUP", 111, "group");
    zzhy = new zzai("HIT_CALLBACK", 112, "hit_callback");
    zzhz = new zzai("HIT_LEVEL_FIELDS_TO_SET", 113, "hit_level_fields_to_set");
    zzhA = new zzai("HTML", 114, "html");
    zzhB = new zzai("ID", 115, "id");
    zzhC = new zzai("IGNORED_ORGANIC", 116, "ignored_organic");
    zzhD = new zzai("IGNORED_REF", 117, "ignored_ref");
    zzhE = new zzai("IGNORE_CASE", 118, "ignore_case");
    zzhF = new zzai("INPUT", 119, "input");
    zzhG = new zzai("INPUT_FORMAT", 120, "input_format");
    zzhH = new zzai("INSTANCE_NAME", 121, "instance_name");
    zzhI = new zzai("INSTANCE_LABEL", 122, "instance_label");
    zzhJ = new zzai("INTERNAL", 123, "internal");
    zzhK = new zzai("INTERVAL", 124, "interval");
    zzhL = new zzai("ITEM_SEPARATOR", 125, "item_separator");
    zzhM = new zzai("JAVASCRIPT", 126, "javascript");
    zzhN = new zzai("JSON", 127, "json");
    zzhO = new zzai("KEYWORD", 128, "keyword");
    zzhP = new zzai("KEY_VALUE_SEPARATOR", 129, "key_value_separator");
    zzhQ = new zzai("LABEL", 130, "label");
    zzhR = new zzai("LANGUAGE", 131, "language");
    zzhS = new zzai("LIMIT", 132, "limit");
    zzhT = new zzai("LINK", 133, "link");
    zzhU = new zzai("LINK_BY_POST", 134, "link_by_post");
    zzhV = new zzai("LINK_ID", 135, "link_id");
    zzhW = new zzai("LIVE_ONLY", 136, "live_only");
    zzhX = new zzai("LOCAL_GIF_PATH", 137, "local_gif_path");
    zzhY = new zzai("LOCALE", 138, "locale");
    zzhZ = new zzai("LOCATION", 139, "location");
    zzia = new zzai("MALWARE_DISABLED", 140, "malware_disabled");
    zzib = new zzai("MAP", 141, "map");
    zzic = new zzai("MAX", 142, "max");
    zzid = new zzai("METRIC", 143, "metric");
    zzie = new zzai("MIN", 144, "min");
    zzif = new zzai("MODE", 145, "mode");
    zzig = new zzai("NAME", 146, "name");
    zzih = new zzai("NAMESPACE_CODE", 147, "namespace_code");
    zzii = new zzai("NAMESPACE_ID", 148, "namespace_id");
    zzij = new zzai("NAMESPACE_VALUE", 149, "namespace_value");
    zzik = new zzai("NEW_STATE", 150, "new_state");
    zzil = new zzai("NONINTERACTION", 151, "noninteraction");
    zzim = new zzai("NOT_DEFAULT_MACRO", 152, "not_default_macro");
    zzin = new zzai("NO_PADDING", 153, "no_padding");
    zzio = new zzai("NUMBER", 154, "number");
    zzip = new zzai("ONCE_PER_EVENT", 155, "once_per_event");
    zziq = new zzai("ONCE_PER_LOAD", 156, "once_per_load");
    zzir = new zzai("OPTOUT", 157, "optout");
    zzis = new zzai("ORDER", 158, "order");
    zzit = new zzai("ORDER_ID", 159, "order_id");
    zziu = new zzai("ORDER_VALUE", 160, "order_value");
    zziv = new zzai("ORDINAL", 161, "ordinal");
    zziw = new zzai("ORGANIC", 162, "organic");
    zzix = new zzai("OUTPUT_FORMAT", 163, "output_format");
    zziy = new zzai("PAGE", 164, "page");
    zziz = new zzai("PAGE_PATH", 165, "page_path");
    zziA = new zzai("PARAMS", 166, "params");
    zziB = new zzai("PARTITION", 167, "partition");
    zziC = new zzai("PERCENTAGE", 168, "percentage");
    zziD = new zzai("PIXEL", 169, "pixel");
    zziE = new zzai("PLACEMENT", 170, "placement");
    zziF = new zzai("PLATFORM", 171, "platform");
    zziG = new zzai("POSITION", 172, "position");
    zziH = new zzai("PRICES", 173, "prices");
    zziI = new zzai("PRIORITY", 174, "priority");
    zziJ = new zzai("PRODUCT", 175, "product");
    zziK = new zzai("PRODUCT_DATA", 176, "product_data");
    zziL = new zzai("PRODUCT_ID", 177, "product_id");
    zziM = new zzai("PRODUCT_IDS", 178, "product_ids");
    zziN = new zzai("PRODUCT_SETTING_FIELD_PATH", 179, "product_setting_field_path");
    zziO = new zzai("PUSH_AFTER_EVALUATE", 180, "push_after_evaluate");
    zziP = new zzai("QUANTITY", 181, "quantity");
    zziQ = new zzai("QUERY_KEY", 182, "query_key");
    zziR = new zzai("QUERY_LISTS", 183, "query_lists");
    zziS = new zzai("REFERRER", 184, "referrer");
    zziT = new zzai("REFERRER_OVERRIDE", 185, "referrer_override");
    zziU = new zzai("REQUIRES_CONTENT", 186, "requires_content");
    zziV = new zzai("REVENUE", 187, "revenue");
    zziW = new zzai("SAMPLE_RATE", 188, "sample_rate");
    zziX = new zzai("SECTION_INDEX", 189, "section_index");
    zziY = new zzai("SELECTOR", 190, "selector");
    zziZ = new zzai("SEND_HITS_TO_GOOGLE", 191, "send_hits_to_google");
    zzja = new zzai("SESSION_CONTROL", 192, "session_control");
    zzjb = new zzai("SESSION_COOKIE_TIMEOUT", 193, "session_cookie_timeout");
    zzjc = new zzai("SETUP_TAGS", 194, "setup_tags");
    zzjd = new zzai("SITE_SPEED_SAMPLE_RATE", 195, "site_speed_sample_rate");
    zzje = new zzai("SOCIAL_ACTION", 196, "social_action");
    zzjf = new zzai("SOCIAL_ACTION_TARGET", 197, "social_action_target");
    zzjg = new zzai("SOCIAL_NETWORK", 198, "social_network");
    zzjh = new zzai("SOCIAL_USE_DATA_LAYER", 199, "social_use_data_layer");
    zzji = new zzai("SERVER_SIDE", 200, "server_side");
    zzjj = new zzai("STANDARD_INDUSTRIAL_CLASSIFICATION", 201, "standard_industrial_classification");
    zzjk = new zzai("STRING", 202, "string");
    zzjl = new zzai("STRIP_WWW", 203, "strip_www");
    zzjm = new zzai("TAG_ID", 204, "tag_id");
    zzjn = new zzai("TAG_LIST", 205, "tag_list");
    zzjo = new zzai("TAG_LIST_CONTEXT", 206, "tag_list_context");
    zzjp = new zzai("TAG_LIST_INDEX", 207, "tag_list_index");
    zzjq = new zzai("TAG_REFERENCE", 208, "tag_reference");
    zzjr = new zzai("TARGET_CSS_ID", 209, "target_css_id");
    zzjs = new zzai("TARGET_ELEMENTS", 210, "target_elements");
    zzjt = new zzai("TARGET_SELECTOR", 211, "target_selector");
    zzju = new zzai("TARGET_URL", 212, "target_url");
    zzjv = new zzai("TEARDOWN_TAGS", 213, "teardown_tags");
    zzjw = new zzai("TEXT", 214, "text");
    zzjx = new zzai("TIMING_CATEGORY", 215, "timing_category");
    zzjy = new zzai("TIMING_LABEL", 216, "timing_label");
    zzjz = new zzai("TIMING_SAMPLE_RATE", 217, "timing_sample_rate");
  }
  
  private zzai(String paramString)
  {
    this.zzkk = paramString;
  }
  
  public String toString()
  {
    return this.zzkk;
  }
}


/* Location:              /Users/tom/Downloads/dex2jar-2.0/classes.jar!/com/google/android/gms/internal/zzai.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */